### ISSUE TITLE
No results obtained after step two

### ISSUE THREAD

**Issue by tjcu408** [xinehc/args_oap#15] opened 2023-01-05 03:50 UTC
the files (metadata.txt and extracted.fa) were obtained successfully after the commond line (args_oap stage_one -i input -o output -f fa -t 8), while we got no results after the commond line (args_oap stage_two -i output -t 8) on our own data, the results were show below,[](url)
![image](https://user-images.githubusercontent.com/28550303/210697687-70b9cb2c-39da-4b0b-a7dd-0181e51241d0.png)

**Comment by xinehc** [comment] 2023-01-05 12:04
Hi,

The default value for `--length` in stage-two is 25aa so if your reads are too short (say 75bp), then no one will pass this filter. You may consider changing the cutoffs in stage-two.

**Comment by tjcu408** [comment] 2023-01-05 15:16
The reads in the extracted.fa of my data were 150bp (shown below). And I changed the value of --length to be 15 in stage-two (args_oap stage_two -i args -t 92 --length 15), and no results obtained still. Two weeks ago, all the default command line go well on my one data, while it did not work after I changede the hard disk and rebuild the conda envs.  What is the issues?

(less extracted.fa:
>11_1@0@A00920:381:HCCGFDSXY:2:1101:20012:1391
GCCTGCGGTAACTTTCGCATGGCTGATTGCAGCTGGTTTTGTACTTGCTGCACGGCTTCGTCCGGATCGGTGCCTGCTTTAAAACTTAAAGTGACAGATGCCTGACCGGTGCCACTGCTCTGAGATGACATATACATGAGATTATCGAGG)

**Comment by xinehc** [comment] 2023-01-05 15:37
I can confirm this is a bug. This happens because all your samples are named using integers (e.g. 11.fa/fq).

This commit 4afa4b1f01b2686cfc08457f1748518f4ec89225 should fix the issue.

**Comment by xinehc** [comment] 2023-01-05 16:05
Fixed in 0d0cede0506579bb263f26bda7dbd663c4b90fa5.

**Comment by tjcu408** [comment] 2023-01-06 07:38
Regretally, the default command produce no results still, with the above fixation alone or synergistically.

**Comment by xinehc** [comment] 2023-01-06 09:47
That's wired, did you install the latest commit in your current conda env using `git clone` and then `python setup.py install`? I haven't uploaded 0d0cede0506579bb263f26bda7dbd663c4b90fa5 to bioconda so `conda install` will still load the old version.

If this does not solve your issue, can you show your current env using `conda env list` and send me a minimal reproducible example of your input files?

**Comment by tjcu408** [comment] 2023-01-08 08:58
After testing, the sample names might be the issues, the names of integers was not supported by the current args_oap stage_two, and the pair sample names including R1 and R2 seemly  not accepted too.

**Comment by xinehc** [comment] 2023-01-18 15:13
https://github.com/xinehc/args_oap/releases/tag/v3.2.2

**Closed by xinehc** 2023-01-18 15:13 UTC
